import type { Lang } from "@/data/portfolio";

const strings = {
  fr: {
    navExperience: "Expérience",
    navProjects: "Projets",
    navPath: "Parcours",
    switchLabel: "English",
    switchAria: "Read this site in English",
    contact: "Me contacter",
    cv: "Télécharger mon CV",
    cvFrOnly: "",
    experienceTitle: "Expérience professionnelle",
    resultsTitle: "Ce que j'ai obtenu",
    photosTitle: "Pendant le stage",
    projectsTitle: "Projets",
    projectsIntro: "Les projets marquants ont leur page avec le détail, les figures et les documents. Les autres sont listés plus bas.",
    ongoing: "En cours",
    done: "Terminé",
    readProject: "Lire le projet",
    ongoingTitle: "En cours",
    doneTitle: "Terminés",
    archiveTitle: "Autres projets de l'IPSA et de l'association",
    skyTitle: "Mes images du ciel",
    skyIntro: "Prises ou traitées par moi, au Seestar S50 à Valberg et à partir des données du télescope UniversCity de Calern.",
    skillsTitle: "Compétences",
    languagesTitle: "Langues",
    pathTitle: "Parcours",
    engagementsTitle: "Engagements",
    footerLine: "Ce site est mis à jour au fil des projets.",
    back: "Retour aux projets",
    about: "À propos du projet",
    keyFacts: "En bref",
    gallery: "Images",
    documents: "Documents",
    open: "Ouvrir",
    code: "Code source",
    demo: "Voir la démo",
    close: "Fermer",
    prev: "Image précédente",
    next: "Image suivante",
    enlarge: "Agrandir l'image",
    home: "/",
    projectBase: "/projets",
  },
  en: {
    navExperience: "Experience",
    navProjects: "Projects",
    navPath: "Background",
    switchLabel: "Français",
    switchAria: "Lire ce site en français",
    contact: "Get in touch",
    cv: "Download my CV",
    cvFrOnly: " (French)",
    experienceTitle: "Professional experience",
    resultsTitle: "What I found",
    photosTitle: "During the internship",
    projectsTitle: "Projects",
    projectsIntro: "The main projects have their own page with details, figures and documents. The others are listed below.",
    ongoing: "Ongoing",
    done: "Completed",
    readProject: "Read the project",
    ongoingTitle: "Ongoing",
    doneTitle: "Completed",
    archiveTitle: "Other IPSA and association projects",
    skyTitle: "My images of the sky",
    skyIntro: "Taken or processed by me, with a Seestar S50 in Valberg and from UniversCity telescope data at Calern.",
    skillsTitle: "Skills",
    languagesTitle: "Languages",
    pathTitle: "Background",
    engagementsTitle: "Commitments",
    footerLine: "This site grows with each project.",
    back: "Back to projects",
    about: "About the project",
    keyFacts: "At a glance",
    gallery: "Images",
    documents: "Documents",
    open: "Open",
    code: "Source code",
    demo: "See the demo",
    close: "Close",
    prev: "Previous image",
    next: "Next image",
    enlarge: "Enlarge image",
    home: "/en",
    projectBase: "/en/projets",
  },
} as const;

export type UI = (typeof strings)["fr"] | (typeof strings)["en"];
export const ui = (lang: Lang): UI => strings[lang];
